# Uncomment this line to define a global platform for your project
platform :ios, "7.1"

target "SGC" do
    pod 'Harpy'
    pod 'iRate'

end

target "SGC_Tests" do
    pod 'Harpy'
    pod 'iRate'

end
