# Uncomment this line to define a global platform for your project
platform :ios, "7.0"

target "SGC" do
    pod 'Harpy'
    pod 'iRate'
    pod 'AFNetworking', '~> 2.0'

end

target "SGC_Tests" do
    pod 'Harpy'
    pod 'iRate'
    pod 'AFNetworking', '~> 2.0'
end
